name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      cryftgoRepo:
        description: 'cryftgo github repository'
        required: true
        default: 'ava-labs/cryftgo'
      cryftgoBranch:
        description: 'cryftgo branch'
        required: true
        default: 'master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: check out ${{ github.event.inputs.cryftgoRepo }} ${{ github.event.inputs.cryftgoBranch }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.cryftgoRepo }}
          ref: ${{ github.event.inputs.cryftgoBranch }}
          path: cryftgo
          token: ${{ secrets.AVALANCHE_PAT }}
      - uses: actions/setup-go@v5
        with:
          go-version: '~1.21.9'
          check-latest: true
      - name: change cryftgo dep
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          go mod edit -replace github.com/shubhamdubey02/cryftgo=./cryftgo
          go mod tidy
          go clean -modcache # avoid conflicts with the golangci-lint-action cache
      - run: ./scripts/lint_allowed_geth_imports.sh
        shell: bash
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56
          working-directory: .
          args: --timeout 3m
          skip-pkg-cache: true
      - name: Run shellcheck
        shell: bash
        run: scripts/shellcheck.sh
  test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-20.04, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: check out ${{ github.event.inputs.cryftgoRepo }} ${{ github.event.inputs.cryftgoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.cryftgoRepo }}
        ref: ${{ github.event.inputs.cryftgoBranch }}
        path: cryftgo
        token: ${{ secrets.AVALANCHE_PAT }}
    - uses: actions/setup-go@v5
      with:
        go-version: '~1.21.9'
        check-latest: true
    - name: change cryftgo dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/shubhamdubey02/cryftgo=./cryftgo
        go mod tidy
    - name: Set timeout on Windows # Windows UT run slower and need a longer timeout
      shell: bash
      if: matrix.os == 'windows-latest'
      run: echo "TIMEOUT=1200s" >> $GITHUB_ENV
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh
      shell: bash
      env:
        TIMEOUT: ${{ env.TIMEOUT }}
    - run: ./scripts/coverage.sh
      shell: bash
  cryftgo_e2e:
    name: CryftGo E2E Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@v4
    - name: check out ${{ github.event.inputs.cryftgoRepo }} ${{ github.event.inputs.cryftgoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.cryftgoRepo }}
        ref: ${{ github.event.inputs.cryftgoBranch }}
        path: cryftgo
        token: ${{ secrets.AVALANCHE_PAT }}
    - uses: actions/setup-go@v5
      with:
        go-version: '~1.21.9'
        check-latest: true
    - name: Run e2e tests
      run: E2E_SERIAL=1 ./scripts/tests.e2e.sh
      shell: bash
    - name: Upload tmpnet network dir
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tmpnet-data
        path: ~/.tmpnet/networks/1000
